# EXAMPLES CAN BE FOUND HERE
# https://github.com/numpy/numpy/blob/master/.travis.yml


os: linux
dist: xenial
language: python

# Travis allows these packages, additions can be requested
#   https://github.com/travis-ci/apt-package-safelist
addons:
  apt:
    packages:
      - libudev-dev

jobs:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=py36
    #   #after_success: coveralls
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
    - python: "3.8"
      env: TOXENV=py38
      dist: xenial
    - python: "3.9-dev"
      env: TOXENV=py39
      dist: xenial
      if: branch = dev AND type = push
  allow_failures:
    - python: "3.9-dev"
      env: TOXENV=py39
      dist: xenial



cache:
  directories:
    - $HOME/.cache/pip
    - "node_modules"
before_install:
  - sudo apt-get update
  - sudo apt-get install portaudio19-dev # Install portaudio (requirement for pyaudio)
install:
  - yarn install
  - pip install tox-travis
  - pip install -r docs/requirements_docs.txt

script:
  # Build the frontend first
  - yarn run build
  # Then, build the backend
  - travis_wait 30 tox --develop
  # Finally, build the docs
  - travis-sphinx build --nowarn --source=docs

after_success:
  - travis-sphinx deploy
