sudo: false
addons:
  apt:
    packages:
      - libudev-dev
matrix:
  fast_finish: true
  include:
    -
      language: python
      python: "3.6"
      env: TOXENV=py36
      script: travis_wait 30 tox --develop
      install:
        - pip install -U tox coveralls
      before_install:
        - sudo apt-get update
        # install portaudio as requirement for pyaudio
        - sudo apt-get install portaudio19-dev
    -
      language: python
      python: "3.7"
      env: TOXENV=py37
      dist: xenial
      script: travis_wait 30 tox --develop
      install:
        - pip install -U tox coveralls
      before_install:
        - sudo apt-get update
        # install portaudio as requirement for pyaudio
        - sudo apt-get install portaudio19-dev
    -
      language: node_js
      script:
        - npm run build
        - npm run test
      install:
        - npm install
        
cache:
  directories:
    - $HOME/.cache/pip
    - node_modules
