crossfade: 1.0
custom_presets: {}
dev_mode: false
devices:
- config:
    center_offset: 0
    channel_count: 207
    channel_offset: 0
    force_refresh: false
    ip_address: 192.168.1.172
    max_brightness: 1.0
    name: WLED-Monitor-1
    pixel_count: 69
    preview_only: false
    refresh_rate: 60
    universe: 1
    universe_end: 1
    universe_size: 512
  id: wled-monitor-1
  type: e131
- config:
    center_offset: 0
    channel_count: 207
    channel_offset: 0
    force_refresh: false
    ip_address: 192.168.1.173
    max_brightness: 1.0
    name: WLED-Monitor-2
    pixel_count: 69
    preview_only: false
    refresh_rate: 60
    universe: 1
    universe_end: 1
    universe_size: 512
  id: wled-monitor-2
  type: e131
- config:
    center_offset: 0
    channel_count: 120
    channel_offset: 0
    force_refresh: false
    ip_address: 192.168.1.171
    max_brightness: 1
    name: WLED-Desk
    pixel_count: 40
    preview_only: false
    refresh_rate: 60
    type: e131
    universe: 1
    universe_end: 1
    universe_size: 512
  id: wled-desk
  type: e131
- config:
    center_offset: 0
    channel_count: 108
    channel_offset: 0
    force_refresh: false
    ip_address: 192.168.1.175
    max_brightness: 1.0
    name: WLED-Temp
    pixel_count: 36
    preview_only: false
    refresh_rate: 60
    universe: 1
    universe_end: 1
    universe_size: 512
  id: wled-temp
  type: e131
- config:
    center_offset: 0
    channel_count: 18
    channel_offset: 0
    force_refresh: false
    ip_address: 192.168.1.174
    max_brightness: 1.0
    name: WLED-Mobile
    pixel_count: 6
    preview_only: false
    refresh_rate: 60
    universe: 1
    universe_end: 1
    universe_size: 512
  id: wled-mobile
  type: e131
- config:
    center_offset: 0
    channel_count: 165
    channel_offset: 0
    force_refresh: false
    ip_address: 192.168.1.176
    max_brightness: 1.0
    name: WLED-TV
    pixel_count: 55
    preview_only: false
    refresh_rate: 60
    universe: 1
    universe_end: 1
    universe_size: 512
  id: wled-tv
  type: e131
- config:
    center_offset: 0
    channel_count: 108
    channel_offset: 0
    force_refresh: false
    ip_address: 192.168.1.177
    max_brightness: 1.0
    name: WLED-Couch
    pixel_count: 36
    preview_only: false
    refresh_rate: 60
    universe: 1
    universe_end: 1
    universe_size: 512
  id: wled-couch
  type: e131
fade: 1.0
host: 0.0.0.0
integrations: []
max_workers: 10
port: 8888
scenes: {}
virtuals:
- items:
  - config:
      center_offset: 0
      channel_count: 207
      channel_offset: 0
      force_refresh: false
      ip_address: 192.168.1.172
      max_brightness: 1
      name: WLED-Monitor-1
      pixel_count: 69
      preview_only: false
      refresh_rate: 60
      universe: 1
      universe_end: 1
      universe_size: 512
    device_key: wled-monitor-1
    effect:
      active: false
    id: wled-monitor-1_0dbc1e50-4991-11eb-9ff7-8b1b61213e51
    invert: true
    key: wled-monitor-1_0dbc1e50-4991-11eb-9ff7-8b1b61213e51
    led_end: 69
    led_start: 49
    name: WLED-Monitor-1
    order_number: 0
    pixel_density: 60
    type: e131
    used_pixel: 21
  - config:
      center_offset: 0
      channel_count: 207
      channel_offset: 0
      force_refresh: false
      ip_address: 192.168.1.172
      max_brightness: 1
      name: WLED-Monitor-1
      pixel_count: 69
      preview_only: false
      refresh_rate: 60
      universe: 1
      universe_end: 1
      universe_size: 512
    device_key: wled-monitor-1
    effect:
      active: false
    id: wled-monitor-1_d75c9150-4963-11eb-86a6-37f2934daaa2
    invert: true
    key: wled-monitor-1_d75c9150-4963-11eb-86a6-37f2934daaa2
    led_end: 48
    led_start: 1
    name: WLED-Monitor-1
    order_number: 1
    pixel_density: 15
    type: e131
    used_pixel: 48
  - config:
      center_offset: 0
      channel_count: 207
      channel_offset: 0
      force_refresh: false
      ip_address: 192.168.1.173
      max_brightness: 1
      name: WLED-Monitor-2
      pixel_count: 69
      preview_only: false
      refresh_rate: 60
      universe: 1
      universe_end: 1
      universe_size: 512
    device_key: wled-monitor-2
    effect:
      active: false
    id: wled-monitor-2_d91fec30-4963-11eb-86a6-37f2934daaa2
    invert: true
    key: wled-monitor-2_d91fec30-4963-11eb-86a6-37f2934daaa2
    led_end: 69
    led_start: 22
    name: WLED-Monitor-2
    order_number: 2
    pixel_density: 60
    type: e131
    used_pixel: 48
  - config:
      center_offset: 0
      channel_count: 207
      channel_offset: 0
      force_refresh: false
      ip_address: 192.168.1.173
      max_brightness: 1
      name: WLED-Monitor-2
      pixel_count: 69
      preview_only: false
      refresh_rate: 60
      universe: 1
      universe_end: 1
      universe_size: 512
    device_key: wled-monitor-2
    effect:
      active: false
    id: wled-monitor-2_192ff130-4991-11eb-9ff7-8b1b61213e51
    invert: true
    key: wled-monitor-2_192ff130-4991-11eb-9ff7-8b1b61213e51
    led_end: 21
    led_start: 1
    name: WLED-Monitor-2
    order_number: 3
    pixel_density: 30
    type: e131
    used_pixel: 21
  name: BladeMod
  pixel_count: 138
- items:
  - config:
      center_offset: 0
      channel_count: 120
      channel_offset: 0
      force_refresh: false
      ip_address: 192.168.1.171
      max_brightness: 1
      name: WLED-Desk
      pixel_count: 40
      preview_only: false
      refresh_rate: 60
      type: e131
      universe: 1
      universe_end: 1
      universe_size: 512
    device_key: wled-desk
    effect:
      active: false
    id: wled-desk_8fb7c3f0-49dc-11eb-80af-9b3fc2dadb03
    invert: false
    key: wled-desk_8fb7c3f0-49dc-11eb-80af-9b3fc2dadb03
    led_end: 40
    led_start: 1
    name: WLED-Desk
    order_number: 0
    pixel_density: 30
    type: e131
    used_pixel: 40
  - config:
      center_offset: 0
      channel_count: 207
      channel_offset: 0
      force_refresh: false
      ip_address: 192.168.1.172
      max_brightness: 1
      name: WLED-Monitor-1
      pixel_count: 69
      preview_only: false
      refresh_rate: 60
      universe: 1
      universe_end: 1
      universe_size: 512
    device_key: wled-monitor-1
    effect:
      active: false
    id: wled-monitor-1_c2dbe160-49cf-11eb-acd8-2b1698c0a815
    invert: true
    key: wled-monitor-1_c2dbe160-49cf-11eb-acd8-2b1698c0a815
    led_end: 69
    led_start: 1
    name: WLED-Monitor-1
    order_number: 1
    pixel_density: 60
    type: e131
    used_pixel: 69
  - config:
      center_offset: 0
      channel_count: 207
      channel_offset: 0
      force_refresh: false
      ip_address: 192.168.1.173
      max_brightness: 1
      name: WLED-Monitor-2
      pixel_count: 69
      preview_only: false
      refresh_rate: 60
      universe: 1
      universe_end: 1
      universe_size: 512
    device_key: wled-monitor-2
    effect:
      active: false
    id: wled-monitor-2_8cc733b0-49dc-11eb-80af-9b3fc2dadb03
    invert: true
    key: wled-monitor-2_8cc733b0-49dc-11eb-80af-9b3fc2dadb03
    led_end: 69
    led_start: 1
    name: WLED-Monitor-2
    order_number: 2
    pixel_density: 60
    type: e131
    used_pixel: 69
  - config:
      center_offset: 0
      channel_count: 18
      channel_offset: 0
      force_refresh: false
      ip_address: 192.168.1.174
      max_brightness: 1
      name: WLED-Mobile
      pixel_count: 6
      preview_only: false
      refresh_rate: 60
      universe: 1
      universe_end: 1
      universe_size: 512
    device_key: wled-mobile
    effect:
      active: false
    id: wled-mobile_95ffe3a0-49dc-11eb-80af-9b3fc2dadb03
    invert: false
    key: wled-mobile_95ffe3a0-49dc-11eb-80af-9b3fc2dadb03
    led_end: 6
    led_start: 1
    name: WLED-Mobile
    order_number: 3
    pixel_density: 15
    type: e131
    used_pixel: 6
  - config:
      center_offset: 0
      channel_count: 108
      channel_offset: 0
      force_refresh: false
      ip_address: 192.168.1.175
      max_brightness: 1
      name: WLED-Temp
      pixel_count: 36
      preview_only: false
      refresh_rate: 60
      universe: 1
      universe_end: 1
      universe_size: 512
    device_key: wled-temp
    effect:
      active: false
    id: wled-temp_9acb4e60-49dc-11eb-80af-9b3fc2dadb03
    invert: false
    key: wled-temp_9acb4e60-49dc-11eb-80af-9b3fc2dadb03
    led_end: 36
    led_start: 1
    name: WLED-Temp
    order_number: 4
    pixel_density: 30
    type: e131
    used_pixel: 36
  - config:
      center_offset: 0
      channel_count: 165
      channel_offset: 0
      force_refresh: false
      ip_address: 192.168.1.176
      max_brightness: 1
      name: WLED-TV
      pixel_count: 55
      preview_only: false
      refresh_rate: 60
      universe: 1
      universe_end: 1
      universe_size: 512
    device_key: wled-tv
    effect:
      active: false
    id: wled-tv_9ddd7060-49dc-11eb-80af-9b3fc2dadb03
    invert: false
    key: wled-tv_9ddd7060-49dc-11eb-80af-9b3fc2dadb03
    led_end: 55
    led_start: 1
    name: WLED-TV
    order_number: 5
    pixel_density: 30
    type: e131
    used_pixel: 55
  - config:
      center_offset: 0
      channel_count: 108
      channel_offset: 0
      force_refresh: false
      ip_address: 192.168.1.177
      max_brightness: 1
      name: WLED-Couch
      pixel_count: 36
      preview_only: false
      refresh_rate: 60
      universe: 1
      universe_end: 1
      universe_size: 512
    device_key: wled-couch
    effect:
      active: false
    id: wled-couch_9fb64f10-49dc-11eb-80af-9b3fc2dadb03
    invert: true
    key: wled-couch_9fb64f10-49dc-11eb-80af-9b3fc2dadb03
    led_end: 36
    led_start: 1
    name: WLED-Couch
    order_number: 6
    pixel_density: 30
    type: e131
    used_pixel: 36
  name: RealWorld
  pixel_count: 311
