crossfade: 1.0
custom_presets: {}
dev_mode: false
devices:
- config:
    center_offset: 0
    channel_count: 207
    channel_offset: 0
    icon_name: SettingsInputComponent
    ip_address: 192.168.1.172
    max_brightness: 1.0
    name: wled 1
    pixel_count: 69
    refresh_rate: 60
    universe: 1
    universe_end: 1
    universe_size: 510
  id: wled-1
  type: e131
- config:
    center_offset: 0
    channel_count: 204
    channel_offset: 0
    icon_name: SettingsInputComponent
    ip_address: 192.168.1.173
    max_brightness: 1.0
    name: wled 2
    pixel_count: 68
    refresh_rate: 60
    universe: 1
    universe_end: 1
    universe_size: 510
  id: wled-2
  type: e131
- config:
    center_offset: 0
    channel_count: 117
    channel_offset: 0
    icon_name: SettingsInputComponent
    ip_address: 192.168.1.175
    max_brightness: 1.0
    name: wled device
    pixel_count: 39
    refresh_rate: 60
    universe: 1
    universe_end: 1
    universe_size: 510
  id: wled-device
  type: e131
displays:
- config:
    center_offset: 0
    crossfade: 1.0
    max_brightness: 1.0
    name: wled 1 Display
    preview_only: false
  id: wled-1-display
  segments:
  - - wled-1
    - 0
    - 68
    - false
- config:
    center_offset: 0
    crossfade: 1.0
    max_brightness: 1.0
    name: wled 2 Display
    preview_only: false
  id: wled-2-display
  segments:
  - - wled-2
    - 0
    - 67
    - false
- config:
    center_offset: 0
    crossfade: 1.0
    max_brightness: 1.0
    name: wled device Display
    preview_only: false
  id: wled-device-display
  segments:
  - - wled-device
    - 0
    - 38
    - false
fade: 1.0
host: 0.0.0.0
integrations: []
max_workers: 10
port: 8888
scenes: {}
virtuals: []
