name: Build LEDFx Docs

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  jobs:         
    - name: Sphinx Build
      uses: ammaraskar/sphinx-action@0.4
            